module.exports = {
  apps: [
    {
      name: "web-ticketing-staging",
      script: "node_modules/.bin/next",
      args: "start",
      cwd: "/var/www/stag.genreklaten.web.id",
      env: {
        PORT: 3001,
        NODE_ENV: "staging",
        APP_ENV: "staging",
      },
      env_file: ".env.staging",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "512M",
      error_file: "logs/staging-err.log",
      out_file: "logs/staging-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
    {
      name: "web-ticketing-prod",
      script: "node_modules/.bin/next",
      args: "start",
      cwd: "/var/www/genreklaten.web.id",
      env: {
        PORT: 3000,
        NODE_ENV: "production",
        APP_ENV: "production",
      },
      env_file: ".env.production",
      instances: "max",
      exec_mode: "cluster",
      watch: false,
      max_memory_restart: "1G",
      error_file: "logs/prod-err.log",
      out_file: "logs/prod-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
  ],
};